name: deeplynks
description: "A Flutter package for deep links, enabling app redirection or store downloads if not installed, while preserving link data through the installation process."
homepage: https://github.com/valueoutput-team/flutter_packages/tree/deeplynks
repository: https://github.com/valueoutput-team/flutter_packages/tree/deeplynks
version: 1.0.4

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
